apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbservice.type }}
  ports:
    - port: {{ .Values.dbservice.port }}
      targetPort: {{ .Values.dbservice.port }}
  selector:
    app: {{ include "flask-app.name" . }}