apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "flask-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-app.fullname" . }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ include "flask-app.fullname" . }}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_USER
              value: {{ .Values.mysql.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.MYSQL_PASSWORD }}
            - name: MYSQL_HOST
              value: {{ .Values.mysql.MYSQL_HOST }}
            - name: MYSQL_DB
              value: {{ .Values.mysql.MYSQL_DATABASE }}
