{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flask-app.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size | quote }}
{{- end }}