apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.MYSQL_DATABASE | b64enc | quote }}
